// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQ-_WUZ6oge69FU5v8isZNRYdn8yfR0Q',
    appId: '1:689785285256:web:0315f676b2e653a83e8d3d',
    messagingSenderId: '689785285256',
    projectId: 'brainbuster-84241',
    authDomain: 'brainbuster-84241.firebaseapp.com',
    storageBucket: 'brainbuster-84241.firebasestorage.app',
    measurementId: 'G-844ZN88FDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz6o1xrCsmAT_BoLf0mloEePoW4tnnLOY',
    appId: '1:689785285256:android:dd10e1ab7b9343113e8d3d',
    messagingSenderId: '689785285256',
    projectId: 'brainbuster-84241',
    storageBucket: 'brainbuster-84241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbJBWhLCOGVB5gUDF3DrXQQGE4koprwg',
    appId: '1:689785285256:ios:4c416136d9db31383e8d3d',
    messagingSenderId: '689785285256',
    projectId: 'brainbuster-84241',
    storageBucket: 'brainbuster-84241.firebasestorage.app',
    iosBundleId: 'com.example.brainbuster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPbJBWhLCOGVB5gUDF3DrXQQGE4koprwg',
    appId: '1:689785285256:ios:4c416136d9db31383e8d3d',
    messagingSenderId: '689785285256',
    projectId: 'brainbuster-84241',
    storageBucket: 'brainbuster-84241.firebasestorage.app',
    iosBundleId: 'com.example.brainbuster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQ-_WUZ6oge69FU5v8isZNRYdn8yfR0Q',
    appId: '1:689785285256:web:24b91b76f21e25283e8d3d',
    messagingSenderId: '689785285256',
    projectId: 'brainbuster-84241',
    authDomain: 'brainbuster-84241.firebaseapp.com',
    storageBucket: 'brainbuster-84241.firebasestorage.app',
    measurementId: 'G-Q0WPFN4HT9',
  );
}
